export const initialState = {
  language: "Ua",
  defaultData: [
    {
      id: 1,
      name: "Капсули Ariel (33 шт/упак.)",
      category: "capsules",
      subcategory: "ariel",
      amount_1: 1,
      amount_2: 3,
      amount_3: 9,
      price_1: 220,
      price_2: 210,
      price_3: 198,
    },
    {
      id: 2,
      name: "A+",
      capacity: "3.905",
      category: "gel",
      subcategory: "optimal",
      amount_1: 4,
      amount_2: 12,
      amount_3: 20,
      price_1: 120,
      price_2: 110,
      price_3: 100,
    },
    {
      id: 3,
      name: "Ariel",
      capacity: "3.905",
      category: "gel",
      subcategory: "lenor",
      amount_1: 4,
      amount_2: 12,
      amount_3: 20,
      price_1: 120,
      price_2: 110,
      price_3: 100,
    },
    {
      id: 4,
      name: "Ariel",
      capacity: "3.905",
      category: "gel",
      subcategory: "touch of fresh",
      amount_1: 4,
      amount_2: 12,
      amount_3: 20,
      price_1: 120,
      price_2: 110,
      price_3: 100,
    },
    {
      id: 5,
      name: "Ariel",
      capacity: "3.905",
      category: "gel",
      subcategory: "mountain spring",
      amount_1: 4,
      amount_2: 12,
      amount_3: 20,
      price_1: 120,
      price_2: 110,
      price_3: 100,
    },
    {
      id: 6,
      name: "Ariel",
      capacity: "3.905",
      category: "gel",
      subcategory: "color and style",
      amount_1: 4,
      amount_2: 12,
      amount_3: 20,
      price_1: 120,
      price_2: 110,
      price_3: 100,
    },
    {
      id: 7,
      name: "A+",
      capacity: "3.905",
      category: "gel",
      subcategory: "fresh flowers",
      amount_1: 4,
      amount_2: 12,
      amount_3: 20,
      price_1: 120,
      price_2: 110,
      price_3: 100,
    },
    {
      id: 8,
      name: "Ariel",
      capacity: "5.81",
      category: "gel",
      subcategory: "lenor",
      amount_1: 1,
      amount_2: 3,
      amount_3: 12,
      amount_4: 30,
      amount_5: 108,
      price_1: 120,
      price_2: 100,
      price_3: 90,
      price_4: 85,
      price_5: 83,
    },
    {
      id: 9,
      name: "Ariel",
      capacity: "5.81",
      category: "gel",
      subcategory: "actilift color",
      amount_1: 1,
      amount_2: 3,
      amount_3: 12,
      amount_4: 30,
      amount_5: 108,
      price_1: 120,
      price_2: 100,
      price_3: 90,
      price_4: 85,
      price_5: 83,
    },
    {
      id: 10,
      name: "Persil",
      capacity: "5.81",
      category: "gel",
      subcategory: "business line",
      amount_1: 1,
      amount_2: 3,
      amount_3: 12,
      amount_4: 30,
      amount_5: 108,
      price_1: 120,
      price_2: 100,
      price_3: 90,
      price_4: 85,
      price_5: 83,
    },
    {
      id: 11,
      name: "Persil",
      capacity: "5.81",
      category: "gel",
      subcategory: "silan",
      amount_1: 1,
      amount_2: 3,
      amount_3: 12,
      amount_4: 30,
      amount_5: 108,
      price_1: 120,
      price_2: 100,
      price_3: 90,
      price_4: 85,
      price_5: 83,
    },
    {
      id: 12,
      name: "Ariel",
      capacity: "5.81",
      category: "gel",
      subcategory: "vollwaschmittel",
      amount_1: 1,
      amount_2: 3,
      amount_3: 12,
      amount_4: 30,
      amount_5: 108,
      price_1: 120,
      price_2: 100,
      price_3: 90,
      price_4: 85,
      price_5: 83,
    },
    {
      id: 13,
      name: "Persil",
      capacity: "5.81",
      category: "gel",
      subcategory: "color gel",
      amount_1: 1,
      amount_2: 3,
      amount_3: 12,
      amount_4: 30,
      amount_5: 108,
      price_1: 120,
      price_2: 100,
      price_3: 90,
      price_4: 85,
      price_5: 83,
    },
    {
      id: 14,
      name: "Dash",
      capacity: "5.775",
      category: "gel",
      subcategory: "color gel",
      amount_1: 1,
      amount_2: 3,
      amount_3: 12,
      amount_4: 30,
      amount_5: 90,
      price_1: 120,
      price_2: 100,
      price_3: 95,
      price_4: 90,
      price_5: 85,
    },
    {
      id: 15,
      name: "Persil",
      capacity: "5.775",
      category: "gel",
      subcategory: "universal",
      amount_1: 1,
      amount_2: 3,
      amount_3: 12,
      amount_4: 30,
      amount_5: 90,
      price_1: 120,
      price_2: 100,
      price_3: 95,
      price_4: 90,
      price_5: 85,
    },
    {
      id: 16,
      name: "Persil",
      capacity: "5.775",
      category: "gel",
      subcategory: "color gel (silan)",
      amount_1: 1,
      amount_2: 3,
      amount_3: 12,
      amount_4: 30,
      amount_5: 90,
      price_1: 120,
      price_2: 100,
      price_3: 95,
      price_4: 90,
      price_5: 85,
    },
    {
      id: 17,
      name: "Ariel",
      capacity: "5.775",
      category: "gel",
      subcategory: "3d actives color&white",
      amount_1: 1,
      amount_2: 3,
      amount_3: 12,
      amount_4: 30,
      amount_5: 90,
      price_1: 120,
      price_2: 100,
      price_3: 95,
      price_4: 90,
      price_5: 85,
    },
    {
      id: 18,
      name: "Ariel",
      capacity: "5.775",
      category: "gel",
      subcategory: "lenor",
      amount_1: 1,
      amount_2: 3,
      amount_3: 12,
      amount_4: 30,
      amount_5: 90,
      price_1: 120,
      price_2: 100,
      price_3: 95,
      price_4: 90,
      price_5: 85,
    },
    {
      id: 19,
      name: "Ariel",
      capacity: "5.775",
      category: "gel",
      subcategory: "color",
      amount_1: 1,
      amount_2: 3,
      amount_3: 12,
      amount_4: 30,
      amount_5: 90,
      price_1: 120,
      price_2: 100,
      price_3: 95,
      price_4: 90,
      price_5: 85,
    },
    {
      id: 20,
      name: "Ariel",
      capacity: "5.775",
      category: "gel",
      subcategory: "mountain spring",
      amount_1: 1,
      amount_2: 3,
      amount_3: 12,
      amount_4: 30,
      amount_5: 90,
      price_1: 120,
      price_2: 100,
      price_3: 95,
      price_4: 90,
      price_5: 85,
    },
    {
      id: 21,
      name: "Ariel",
      capacity: "5.775",
      category: "gel",
      subcategory: "universal",
      amount_1: 1,
      amount_2: 3,
      amount_3: 12,
      amount_4: 30,
      amount_5: 90,
      price_1: 120,
      price_2: 100,
      price_3: 95,
      price_4: 90,
      price_5: 85,
    },
    {
      id: 22,
      name: "Lenor",
      capacity: "5.775",
      category: "gel",
      subcategory: "2in1",
      amount_1: 1,
      amount_2: 3,
      amount_3: 12,
      amount_4: 30,
      amount_5: 90,
      price_1: 120,
      price_2: 100,
      price_3: 95,
      price_4: 90,
      price_5: 85,
    },
    {
      id: 23,
      name: "Tide",
      capacity: "5.775",
      category: "gel",
      subcategory: "",
      amount_1: 1,
      amount_2: 3,
      amount_3: 12,
      amount_4: 30,
      amount_5: 90,
      price_1: 120,
      price_2: 100,
      price_3: 95,
      price_4: 90,
      price_5: 85,
    },
    {
      id: 24,
      name: "Ariel",
      capacity: "6.3",
      category: "gel",
      subcategory: "lenor",
      amount_1: 1,
      amount_2: 3,
      amount_3: 9,
      price_1: 200,
      price_2: 180,
      price_3: 160,
    },
    {
      id: 25,
      name: "Ariel",
      capacity: "6.3",
      category: "gel",
      subcategory: "mounting",
      amount_1: 1,
      amount_2: 3,
      amount_3: 9,
      price_1: 200,
      price_2: 180,
      price_3: 160,
    },
    {
      id: 26,
      name: "Ariel",
      capacity: "6.3",
      category: "gel",
      subcategory: "color",
      amount_1: 1,
      amount_2: 3,
      amount_3: 9,
      price_1: 200,
      price_2: 180,
      price_3: 160,
    },
    {
      id: 27,
      name: "Ariel",
      capacity: "6.3",
      category: "gel",
      subcategory: "universal",
      amount_1: 1,
      amount_2: 3,
      amount_3: 9,
      price_1: 200,
      price_2: 180,
      price_3: 160,
    },
    {
      id: 28,
      name: "Persil",
      capacity: "6.3",
      category: "gel",
      subcategory: "color",
      amount_1: 1,
      amount_2: 3,
      amount_3: 9,
      price_1: 200,
      price_2: 180,
      price_3: 160,
    },
    {
      id: 29,
      name: "Perwoll",
      capacity: "6.3",
      category: "gel",
      subcategory: "",
      amount_1: 1,
      amount_2: 3,
      amount_3: 9,
      price_1: 200,
      price_2: 180,
      price_3: 160,
    },
    {
      id: 30,
      name: "Fairy",
      capacity: "6.3",
      category: "gel",
      subcategory: "",
      amount_1: 1,
      amount_2: 3,
      amount_3: 9,
      price_1: 200,
      price_2: 180,
      price_3: 160,
    },
    {
      id: 31,
      name: "Omo",
      capacity: "6.3",
      category: "gel",
      subcategory: "",
      amount_1: 1,
      amount_2: 3,
      amount_3: 9,
      price_1: 200,
      price_2: 180,
      price_3: 160,
    },
    {
      id: 32,
      name: "Dash",
      capacity: "6.3",
      category: "gel",
      subcategory: "",
      amount_1: 1,
      amount_2: 3,
      amount_3: 9,
      price_1: 200,
      price_2: 180,
      price_3: 160,
    },
    {
      id: 33,
      name: "Tide",
      capacity: "6.3",
      category: "gel",
      subcategory: "",
      amount_1: 1,
      amount_2: 3,
      amount_3: 9,
      price_1: 200,
      price_2: 180,
      price_3: 160,
    },
    {
      id: 34,
      name: "Persil",
      capacity: "5.8",
      category: "gel",
      subcategory: "Active gel",
      amount_1: 1,
      amount_2: 12,
      amount_3: 30,
      amount_4: 90,
      price_1: 120,
      price_2: 100,
      price_3: 95,
      price_4: 90,
    },
    {
      id: 35,
      name: "Persil",
      capacity: "5.8",
      category: "gel",
      subcategory: "Universal gel",
      amount_1: 1,
      amount_2: 12,
      amount_3: 30,
      amount_4: 90,
      price_1: 120,
      price_2: 100,
      price_3: 95,
      price_4: 90,
    },
    {
      id: 36,
      name: "Persil",
      capacity: "5.8",
      category: "gel",
      subcategory: "color gel",
      amount_1: 1,
      amount_2: 12,
      amount_3: 30,
      amount_4: 90,
      price_1: 120,
      price_2: 100,
      price_3: 95,
      price_4: 90,
    },
    {
      id: 37,
      name: "Persil",
      capacity: "5.8",
      category: "gel",
      subcategory: "premium gel",
      amount_1: 1,
      amount_2: 12,
      amount_3: 30,
      amount_4: 90,
      price_1: 120,
      price_2: 100,
      price_3: 95,
      price_4: 90,
    },
    {
      id: 38,
      name: "Ariel",
      capacity: "6.0",
      category: "gel",
      subcategory: "Antibacterial",
      amount_1: 1,
      amount_2: 12,
      amount_3: 30,
      amount_4: 90,
      price_1: 120,
      price_2: 100,
      price_3: 95,
      price_4: 90,
    },
    {
      id: 39,
      name: "Ariel",
      capacity: "6.0",
      category: "gel",
      subcategory: "Premium",
      amount_1: 1,
      amount_2: 12,
      amount_3: 30,
      amount_4: 90,
      price_1: 120,
      price_2: 100,
      price_3: 95,
      price_4: 90,
    },
    {
      id: 40,
      name: "Ariel",
      capacity: "6.0",
      category: "gel-box",
      subcategory: "Premium",
      amount_1: 1,
      amount_2: 5,
      amount_3: 10,
      amount_4: 30,
      price_1: 250,
      price_2: 200,
      price_3: 195,
      price_4: 190,
    },
    {
      id: 41,
      name: "Ariel",
      capacity: "6.0",
      category: "gel-box",
      subcategory: "Antibacterial",
      amount_1: 1,
      amount_2: 5,
      amount_3: 10,
      amount_4: 30,
      price_1: 250,
      price_2: 200,
      price_3: 195,
      price_4: 190,
    },
    {
      id: 42,
      name: "Persil",
      capacity: "5.8",
      category: "gel-box",
      subcategory: "universal",
      amount_1: 1,
      amount_2: 5,
      amount_3: 10,
      amount_4: 30,
      price_1: 250,
      price_2: 200,
      price_3: 195,
      price_4: 190,
    },
    {
      id: 43,
      name: "Persil",
      capacity: "5.8",
      category: "gel-box",
      subcategory: "premium",
      amount_1: 1,
      amount_2: 5,
      amount_3: 10,
      amount_4: 30,
      price_1: 250,
      price_2: 200,
      price_3: 195,
      price_4: 190,
    },
    {
      id: 44,
      name: "Persil",
      capacity: "5.8",
      category: "gel-box",
      subcategory: "color gel",
      amount_1: 1,
      amount_2: 5,
      amount_3: 10,
      amount_4: 30,
      price_1: 250,
      price_2: 200,
      price_3: 195,
      price_4: 190,
    },
    {
      id: 45,
      name: "Cocolino",
      capacity: "5.775",
      category: "conditioner",
      subcategory: "lavish blossom",
      amount_1: 1,
      amount_2: 5,
      amount_3: 9,
      amount_4: 12,
      price_1: 150,
      price_2: 130,
      price_3: 125,
      price_4: 110,
    },
    {
      id: 46,
      name: "Cocolino",
      capacity: "5.775",
      category: "conditioner",
      subcategory: "heavenly nectar",
      amount_1: 1,
      amount_2: 5,
      amount_3: 9,
      amount_4: 12,
      price_1: 150,
      price_2: 130,
      price_3: 125,
      price_4: 110,
    },
    {
      id: 47,
      name: "Cocolino",
      capacity: "5.775",
      category: "conditioner",
      subcategory: "luscious bouquet",
      amount_1: 1,
      amount_2: 5,
      amount_3: 9,
      amount_4: 12,
      price_1: 150,
      price_2: 130,
      price_3: 125,
      price_4: 110,
    },
    {
      id: 48,
      name: "Cocolino",
      capacity: "5.775",
      category: "conditioner",
      subcategory: "divine petals",
      amount_1: 1,
      amount_2: 5,
      amount_3: 9,
      amount_4: 12,
      price_1: 150,
      price_2: 130,
      price_3: 125,
      price_4: 110,
    },
    {
      id: 49,
      name: "Persil",
      capacity: "10",
      category: "powder-bag",
      subcategory: "universal",
      amount_1: 1,
      amount_2: 3,
      amount_3: 5,
      amount_4: 10,
      price_1: 230,
      price_2: 180,
      price_3: 170,
      price_4: 160,
    },
    {
      id: 50,
      name: "Ariel",
      capacity: "10",
      category: "powder-bag",
      subcategory: "whites+color",
      amount_1: 1,
      amount_2: 3,
      amount_3: 5,
      amount_4: 10,
      price_1: 230,
      price_2: 180,
      price_3: 170,
      price_4: 160,
    },
    {
      id: 51,
      name: "Ariel",
      capacity: "10",
      category: "powder-bag",
      subcategory: "actilift",
      amount_1: 1,
      amount_2: 3,
      amount_3: 5,
      amount_4: 10,
      price_1: 230,
      price_2: 180,
      price_3: 170,
      price_4: 160,
    },
    {
      id: 52,
      name: "Persil",
      capacity: "10",
      category: "powder-bag",
      subcategory: "color",
      amount_1: 1,
      amount_2: 3,
      amount_3: 5,
      amount_4: 10,
      price_1: 230,
      price_2: 180,
      price_3: 170,
      price_4: 160,
    },
    {
      id: 53,
      name: "Ariel",
      capacity: "10",
      category: "powder-bag",
      subcategory: "alfa",
      amount_1: 1,
      amount_2: 3,
      amount_3: 5,
      amount_4: 10,
      price_1: 230,
      price_2: 180,
      price_3: 170,
      price_4: 160,
    },
    {
      id: 54,
      name: "Ariel",
      capacity: "10",
      category: "powder-bag-vip",
      subcategory: "universal",
      amount_1: 1,
      amount_2: 3,
      amount_3: 5,
      price_1: 260,
      price_2: 190,
      price_3: 180,
    },
    {
      id: 55,
      name: "Ariel",
      capacity: "10",
      category: "powder-bag-vip",
      subcategory: "whites+color",
      amount_1: 1,
      amount_2: 3,
      amount_3: 5,
      price_1: 260,
      price_2: 190,
      price_3: 180,
    },
    {
      id: 56,
      name: "Ariel",
      capacity: "10",
      category: "powder-bag-vip",
      subcategory: "actilift",
      amount_1: 1,
      amount_2: 3,
      amount_3: 5,
      price_1: 260,
      price_2: 190,
      price_3: 180,
    },
    {
      id: 57,
      name: "Persil",
      capacity: "10",
      category: "powder-bag-vip",
      subcategory: "color",
      amount_1: 1,
      amount_2: 3,
      amount_3: 5,
      price_1: 260,
      price_2: 190,
      price_3: 180,
    },
    {
      id: 58,
      name: "Ariel",
      capacity: "10",
      category: "powder-bag-vip",
      subcategory: "alfa",
      amount_1: 1,
      amount_2: 3,
      amount_3: 5,
      price_1: 260,
      price_2: 190,
      price_3: 180,
    },
    {
      id: 59,
      name: "Dash",
      capacity: "11.50",
      category: "powder-bag",
      subcategory: "",
      amount_1: 1,
      amount_2: 3,
      amount_3: 5,
      price_1: 250,
      price_2: 200,
      price_3: 190,
    },
    {
      id: 60,
      name: "Gala",
      capacity: "8",
      category: "powder-bag",
      subcategory: "",
      amount_1: 1,
      amount_2: 3,
      amount_3: 5,
      price_1: 180,
      price_2: 160,
      price_3: 150,
    },
    {
      id: 61,
      name: "Ariel",
      capacity: "6",
      category: "powder-bag",
      subcategory: "color and white",
      amount_1: 1,
      amount_2: 3,
      amount_3: 5,
      amount_4: 10,
      price_1: 136,
      price_2: 116,
      price_3: 106,
      price_4: 101,
    },
    {
      id: 62,
      name: "Persil",
      capacity: "6",
      category: "powder-bag",
      subcategory: "universal",
      amount_1: 1,
      amount_2: 3,
      amount_3: 5,
      amount_4: 10,
      price_1: 136,
      price_2: 116,
      price_3: 106,
      price_4: 101,
    },
    {
      id: 63,
      name: "Ariel",
      capacity: "6",
      category: "powder-bag-vip",
      subcategory: "color and white",
      amount_1: 1,
      amount_2: 3,
      amount_3: 5,
      price_1: 136,
      price_2: 121,
      price_3: 111,
    },
    {
      id: 62,
      name: "Persil",
      capacity: "6",
      category: "powder-bag-vip",
      subcategory: "universal",
      amount_1: 1,
      amount_2: 3,
      amount_3: 5,
      price_1: 136,
      price_2: 121,
      price_3: 111,
    },
    {
      id: 63,
      name: "Ariel",
      capacity: "6.8",
      category: "powder-box",
      subcategory: "pro&frais",
      amount_1: 1,
      amount_2: 3,
      amount_3: 5,
      price_1: 155,
      price_2: 145,
      price_3: 135,
    },
    {
      id: 64,
      name: "Ariel",
      capacity: "6.8",
      category: "powder-box-vip",
      subcategory: "pro&frais",
      amount_1: 1,
      amount_2: 3,
      amount_3: 5,
      price_1: 170,
      price_2: 160,
      price_3: 145,
    },
    {
      id: 65,
      name: "Ariel",
      capacity: "10",
      category: "powder-box",
      subcategory: "traditional",
      amount_1: 1,
      amount_2: 3,
      amount_3: 5,
      price_1: 230,
      price_2: 180,
      price_3: 170,
    },
    {
      id: 66,
      name: "Ariel",
      capacity: "10",
      category: "powder-box",
      subcategory: "actilift color",
      amount_1: 1,
      amount_2: 3,
      amount_3: 5,
      price_1: 230,
      price_2: 180,
      price_3: 170,
    },
    {
      id: 67,
      name: "Ariel",
      capacity: "10",
      category: "powder-box-vip",
      subcategory: "traditional",
      amount_1: 1,
      amount_2: 3,
      amount_3: 5,
      price_1: 260,
      price_2: 190,
      price_3: 180,
    },
    {
      id: 68,
      name: "Ariel",
      capacity: "10",
      category: "powder-box-vip",
      subcategory: "actilift color",
      amount_1: 1,
      amount_2: 3,
      amount_3: 5,
      price_1: 260,
      price_2: 190,
      price_3: 180,
    },
    {
      id: 69,
      name: "Ariel",
      capacity: "10",
      category: "powder-bucket",
      subcategory: "colour",
      amount_1: 1,
      amount_2: 3,
      amount_3: 5,
      price_1: 230,
      price_2: 190,
      price_3: 180,
    },
    {
      id: 70,
      name: "Ariel",
      capacity: "10",
      category: "powder-bucket",
      subcategory: "actilift",
      amount_1: 1,
      amount_2: 3,
      amount_3: 5,
      price_1: 230,
      price_2: 190,
      price_3: 180,
    },
    {
      id: 71,
      name: "Persil",
      capacity: "10",
      category: "powder-bucket",
      subcategory: "kalt-aktiv",
      amount_1: 1,
      amount_2: 3,
      amount_3: 5,
      price_1: 230,
      price_2: 190,
      price_3: 180,
    },
    {
      id: 72,
      name: "Persil",
      capacity: "10",
      category: "powder-bucket",
      subcategory: "megaperls",
      amount_1: 1,
      amount_2: 3,
      amount_3: 5,
      price_1: 230,
      price_2: 190,
      price_3: 180,
    },
    {
      id: 73,
      name: "Persil",
      capacity: "10",
      category: "powder-bucket",
      subcategory: "gold",
      amount_1: 1,
      amount_2: 3,
      amount_3: 5,
      price_1: 230,
      price_2: 190,
      price_3: 180,
    },
    {
      id: 74,
      name: "Ariel",
      capacity: "10",
      category: "powder-bucket-vip",
      subcategory: "colour",
      amount_1: 1,
      amount_2: 3,
      amount_3: 5,
      price_1: 260,
      price_2: 210,
      price_3: 190,
    },
    {
      id: 75,
      name: "Ariel",
      capacity: "10",
      category: "powder-bucket-vip",
      subcategory: "actilift",
      amount_1: 1,
      amount_2: 3,
      amount_3: 5,
      price_1: 260,
      price_2: 210,
      price_3: 190,
    },
    {
      id: 76,
      name: "Persil",
      capacity: "10",
      category: "powder-bucket-vip",
      subcategory: "kalt-aktiv",
      amount_1: 1,
      amount_2: 3,
      amount_3: 5,
      price_1: 260,
      price_2: 210,
      price_3: 190,
    },
    {
      id: 77,
      name: "Persil",
      capacity: "10",
      category: "powder-bucket-vip",
      subcategory: "megaperls",
      amount_1: 1,
      amount_2: 3,
      amount_3: 5,
      price_1: 260,
      price_2: 210,
      price_3: 190,
    },
    {
      id: 78,
      name: "Persil",
      capacity: "10",
      category: "powder-bucket-vip",
      subcategory: "gold",
      amount_1: 1,
      amount_2: 3,
      amount_3: 5,
      price_1: 260,
      price_2: 210,
      price_3: 190,
    },
    {
      id: 79,
      name: "Ariel",
      capacity: "5",
      category: "powder-bucket",
      subcategory: "colour",
      amount_1: 1,
      amount_2: 3,
      amount_3: 5,
      price_1: 115,
      price_2: 110,
      price_3: 100,
    },
    {
      id: 80,
      name: "Ariel",
      capacity: "5",
      category: "powder-bucket",
      subcategory: "actilift",
      amount_1: 1,
      amount_2: 3,
      amount_3: 5,
      price_1: 115,
      price_2: 110,
      price_3: 100,
    },
    {
      id: 81,
      name: "Persil",
      capacity: "5",
      category: "powder-bucket",
      subcategory: "kalt-aktiv",
      amount_1: 1,
      amount_2: 3,
      amount_3: 5,
      price_1: 115,
      price_2: 110,
      price_3: 100,
    },
    {
      id: 82,
      name: "Persil",
      capacity: "5",
      category: "powder-bucket",
      subcategory: "megaperls",
      amount_1: 1,
      amount_2: 3,
      amount_3: 5,
      price_1: 115,
      price_2: 110,
      price_3: 100,
    },
    {
      id: 83,
      name: "Persil",
      capacity: "5",
      category: "powder-bucket",
      subcategory: "gold",
      amount_1: 1,
      amount_2: 3,
      amount_3: 5,
      price_1: 115,
      price_2: 110,
      price_3: 100,
    },
    {
      id: 84,
      name: "Ariel",
      capacity: "5",
      category: "powder-bucket-vip",
      subcategory: "colour",
      amount_1: 1,
      amount_2: 3,
      amount_3: 5,
      price_1: 135,
      price_2: 125,
      price_3: 115,
    },
    {
      id: 85,
      name: "Ariel",
      capacity: "5",
      category: "powder-bucket-vip",
      subcategory: "actilift",
      amount_1: 1,
      amount_2: 3,
      amount_3: 5,
      price_1: 135,
      price_2: 125,
      price_3: 115,
    },
    {
      id: 86,
      name: "Persil",
      capacity: "5",
      category: "powder-bucket-vip",
      subcategory: "kalt-aktiv",
      amount_1: 1,
      amount_2: 3,
      amount_3: 5,
      price_1: 135,
      price_2: 125,
      price_3: 115,
    },
    {
      id: 87,
      name: "Persil",
      capacity: "5",
      category: "powder-bucket-vip",
      subcategory: "megaperls",
      amount_1: 1,
      amount_2: 3,
      amount_3: 5,
      price_1: 135,
      price_2: 125,
      price_3: 115,
    },
    {
      id: 88,
      name: "Persil",
      capacity: "5",
      category: "powder-bucket-vip",
      subcategory: "gold",
      amount_1: 1,
      amount_2: 3,
      amount_3: 5,
      price_1: 135,
      price_2: 125,
      price_3: 115,
    },
    {
      id: 89,
      name: "Menthol",
      capacity: "400",
      category: "shampoo",
      subcategory: "",
      amount_1: 1,
      amount_2: 3,
      amount_3: 6,
      amount_4: 18,
      price_1: 60,
      price_2: 50,
      price_3: 45,
      price_4: 42,
    },
    {
      id: 90,
      name: "Menthol",
      capacity: "400",
      category: "shampoo",
      subcategory: "classic",
      amount_1: 1,
      amount_2: 3,
      amount_3: 6,
      amount_4: 18,
      price_1: 60,
      price_2: 50,
      price_3: 45,
      price_4: 42,
    },
    {
      id: 91,
      name: "Menthol",
      capacity: "400",
      category: "shampoo",
      subcategory: "citrus",
      amount_1: 1,
      amount_2: 3,
      amount_3: 6,
      amount_4: 18,
      price_1: 60,
      price_2: 50,
      price_3: 45,
      price_4: 42,
    },
    {
      id: 92,
      name: "Head and shoulders",
      capacity: "5",
      category: "shampoo",
      subcategory: "lemon",
      amount_1: 100,
      amount_2: 200,
      amount_3: 300,
      amount_4: 500,
      amount_5: 3360,
      price_1: 2,
      price_2: 1.90,
      price_3: 1.80,
      price_4: 1.70,
      price_5: 1.50,
    },
    {
      id: 93,
      name: "Head and shoulders",
      capacity: "5",
      category: "shampoo",
      subcategory: "basic",
      amount_1: 100,
      amount_2: 200,
      amount_3: 300,
      amount_4: 500,
      amount_5: 3360,
      price_1: 2,
      price_2: 1.90,
      price_3: 1.80,
      price_4: 1.70,
      price_5: 1.50,
    },
    {
      id: 94,
      name: "Head and shoulders",
      capacity: "5",
      category: "shampoo",
      subcategory: "menthol",
      amount_1: 100,
      amount_2: 200,
      amount_3: 300,
      amount_4: 500,
      amount_5: 3360,
      price_1: 2,
      price_2: 1.90,
      price_3: 1.80,
      price_4: 1.70,
      price_5: 1.50,
    },
    {
      id: 95,
      name: "Domestos",
      capacity: "1",
      category: "domestos",
      subcategory: "white",
      amount_1: 1,
      amount_2: 12,
      amount_3: 24,
      price_1: 50,
      price_2: 40,
      price_3: 34,
    },
    {
      id: 96,
      name: "Domestos",
      capacity: "1",
      category: "domestos",
      subcategory: "blue",
      amount_1: 1,
      amount_2: 12,
      amount_3: 24,
      price_1: 50,
      price_2: 40,
      price_3: 34,
    },
    {
      id: 97,
      name: "Domestos",
      capacity: "1",
      category: "domestos",
      subcategory: "green",
      amount_1: 1,
      amount_2: 12,
      amount_3: 24,
      price_1: 50,
      price_2: 40,
      price_3: 34,
    },
    {
      id: 98,
      name: "Domestos",
      capacity: "1",
      category: "domestos",
      subcategory: "yellow",
      amount_1: 1,
      amount_2: 12,
      amount_3: 24,
      price_1: 50,
      price_2: 40,
      price_3: 34,
    },
    {
      id: 99,
      name: "Fairy",
      capacity: "1",
      category: "fairy",
      subcategory: "apple",
      amount_1: 1,
      amount_2: 5,
      amount_3: 10,
      price_1: 50,
      price_2: 30,
      price_3: 28,
    },
    {
      id: 100,
      name: "Fairy",
      capacity: "1",
      category: "fairy",
      subcategory: "lemon",
      amount_1: 1,
      amount_2: 5,
      amount_3: 10,
      price_1: 50,
      price_2: 30,
      price_3: 28,
    },
    {
      id: 101,
      name: "Fairy",
      capacity: "1",
      category: "fairy",
      subcategory: "orange",
      amount_1: 1,
      amount_2: 5,
      amount_3: 10,
      price_1: 50,
      price_2: 30,
      price_3: 28,
    },
    {
      id: 102,
      name: "Fairy",
      capacity: "5",
      category: "fairy",
      subcategory: "apple",
      amount_1: 1,
      amount_2: 4,
      amount_3: 12,
      price_1: 120,
      price_2: 110,
      price_3: 100,
    },
    {
      id: 103,
      name: "Fairy",
      capacity: "5",
      category: "fairy",
      subcategory: "lemon",
      amount_1: 1,
      amount_2: 4,
      amount_3: 12,
      price_1: 120,
      price_2: 110,
      price_3: 100,
    },
    {
      id: 104,
      name: "Fairy",
      capacity: "5",
      category: "fairy",
      subcategory: "berries",
      amount_1: 1,
      amount_2: 4,
      amount_3: 12,
      price_1: 120,
      price_2: 110,
      price_3: 100,
    },
    {
      id: 105,
      name: "Dove",
      capacity: "5",
      category: "soap",
      subcategory: "",
      amount_1: 1,
      amount_2: 4,
      amount_3: 12,
      price_1: 150,
      price_2: 120,
      price_3: 110,
    },
    {
      id: 106,
      name: "Safeguard",
      capacity: "5",
      category: "soap",
      subcategory: "",
      amount_1: 1,
      amount_2: 4,
      amount_3: 12,
      price_1: 150,
      price_2: 120,
      price_3: 110,
    },
  ],
};
